### ISSUE TITLE
Support prefixed labels

### ISSUE THREAD

**Issue by adamralph** [Particular/Automation.Engineering#2]
`Type: ...`, etc.

Similar to https://github.com/Particular/GitHubReleaseNotes/issues/26

- [x] make changes - https://github.com/Particular/Automation.Engineering/issues/1
- [x] release

**Comment by adamralph** [comment]
@SzymonPobiega thanks for the merge. How do I release the new version?

**Comment by SzymonPobiega** [comment]
You need to promote the build to `Deploy` here http://builds.particular.net/project.html?projectId=Operations_Engineering&tab=projectOverview and then, via the Octopus tab, promote it from staging to production.

**Comment by adamralph** [comment]
Done. Thanks!
